# Generated by Django 2.0.5 on 2018-07-27 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(default=0, max_length=100, unique=True)),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('copies', models.IntegerField(default=1)),
                ('notes', models.TextField()),
                ('copies_on_lent', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('magazine', 'Magazine'), ('comics', 'Comics'), ('books', 'Books')], default='books', max_length=10)),
                ('locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
            ],
        ),
    ]
