# Generated by Django 2.0.5 on 2018-08-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('magazine', 'Magazine'), ('comics', 'Comics'), ('educational', 'Educational'), ('books', 'Books')], default='books', max_length=10),
        ),
    ]
