# Generated by Django 2.0.5 on 2018-05-23 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lent_on', models.DateField(auto_now_add=True)),
                ('duration', models.DurationField(default=14)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
            ],
            options={
                'ordering': ('lib_user',),
            },
        ),
        migrations.CreateModel(
            name='LibUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='lent',
            name='lib_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_users.LibUsers'),
        ),
    ]
