# Generated by Django 2.0.5 on 2018-07-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libusers',
            old_name='avatar',
            new_name='user_image',
        ),
    ]
