# Generated by Django 2.0.5 on 2018-07-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_users', '0002_auto_20180728_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libusers',
            old_name='user_image',
            new_name='avatar',
        ),
        migrations.AddField(
            model_name='libusers',
            name='user_type',
            field=models.CharField(choices=[('student', 'STUDENT'), ('teacher', 'TEACHER'), ('default', 'DEFAULT')], default='default', max_length=100),
        ),
    ]
