# Generated by Django 2.0.5 on 2018-07-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_users', '0003_auto_20180728_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libusers',
            name='avatar',
        ),
    ]
