# Generated by Django 2.0.5 on 2018-08-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_users', '0005_libusers_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='libusers',
            name='father',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libusers',
            name='mother',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
