# Generated by Django 2.0.5 on 2018-09-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_users', '0006_auto_20180808_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='libusers',
            name='account_activated',
            field=models.BooleanField(default=False),
        ),
    ]
