# Generated by Django 2.0.5 on 2018-09-22 06:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_users', '0007_libusers_account_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libusers',
            name='avatar',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
    ]
